// Program outline imports SVGs (primarily those generated by KiCad)
// and converts them into polygon.Shapes that outline the overlapping
// input data. It outputs in the form of a gnuplot inline script.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"

	"zappem.net/pub/graphics/svger"
	"zappem.net/pub/graphics/svgpoly"
	"zappem.net/pub/math/polygon"
)

var (
	src      = flag.String("svg", "", "input SVG file")
	poly     = flag.String("poly", "", "input json polygon.Shapes")
	dest     = flag.String("dest", "", "output gnuplot script filename")
	oSVG     = flag.String("osvg", "", "output representation in SVG format")
	oPoly    = flag.String("opoly", "", "output representation of polygons.Shapes in json")
	drop     = flag.String("drop", "", "non-empty is comma list of pre-merge polygon indices to keep")
	flip     = flag.Bool("flip", true, "negate Y values when processing SVGs to/from polygons")
	debug    = flag.Bool("debug", false, "enable more debugging output")
	before   = flag.Bool("before", false, "show polygons before creating union")
	after    = flag.Bool("after", true, "show polygons after creating union")
	scribe   = flag.Float64("scribe", 0.02, "pen scribing size (for rounding circles and --osvg)")
	inflate  = flag.Float64("inflate", 0.0, "inflate outlines by this value")
	hatch    = flag.Float64("hatch", 0.0, "hatch the polygons with this spacing")
	hAngle   = flag.Float64("hatch-angle", 45.0, "hatch pattern is at this angle")
	inverse  = flag.Float64("inverse", 0.0, "inverse with this margin if non-zero")
	outline  = flag.String("outline", "", "outline color override")
	inline   = flag.String("inline", "", "inline color override")
	backing  = flag.String("backing", "", "backing color override")
	hatching = flag.String("hatching", "", "hatching color override")
	fill     = flag.String("fill", "", "shape fill color override")
	hole     = flag.String("hole", "", "hole fill color override")
)

// plotData outputs the polygon data into a gnuplot format.
func plotData(out io.Writer, s *polygon.Shapes, lines ...polygon.Line) {
	if s == nil {
		log.Fatal("Unable to plot empty shapes")
	}
	fmt.Fprintln(out, "# X Y")
	for i, p := range s.P {
		for _, pt := range p.PS {
			fmt.Fprintf(out, "%.3f %.3f\n", pt.X, pt.Y)
		}
		fmt.Fprintf(out, "%.3f %.3f\n", p.PS[0].X, p.PS[0].Y)
		if i != len(s.P)-1 {
			fmt.Fprintln(out)
		}
	}
	for _, line := range lines {
		fmt.Fprintf(out, "\n%.3f %.3f\n%.3f %.3f\n", line.From.X, line.From.Y, line.To.X, line.To.Y)
	}
	fmt.Fprintln(out, "e")
}

func main() {
	log.Default().SetFlags(log.Lshortfile | log.Ldate | log.Lmicroseconds)
	flag.Parse()
	svger.Debug = *debug

	// shapes are closed (filled) polygons.
	// cuts are outlines with no substance.
	var shapes, cuts *polygon.Shapes
	var err error
	if *poly != "" {
		var d []byte
		d, err = os.ReadFile(*poly)
		var objects polygon.Shapes
		if err == nil {
			err = json.Unmarshal(d, &objects)
			if err == nil {
				shapes = &objects
			}
		}
	} else {
		shapes, cuts, err = svgpoly.LoadSVG(*src, *scribe)
		if *flip {
			shapes = svgpoly.Flip(shapes)
			cuts = svgpoly.Flip(cuts)
		}
	}
	if err != nil {
		log.Fatalf("Failed to load --svg=%q: %v", *src, err)
	}

	if *drop != "" {
		var prune []int
		for _, v := range strings.Split(*drop, ",") {
			x, err := strconv.Atoi(v)
			if err != nil {
				log.Fatalf("--drop=...%q... ?: %v", v, err)
			}
			if x < 0 || x >= len(shapes.P) {
				log.Fatalf("--drop=...%d... out of range [%d,%d)", x, 0, len(shapes.P))
			}
			prune = append(prune, x)
		}
		sort.Slice(prune, func(a, b int) bool { return prune[a] > prune[b] })
		for _, x := range prune {
			if x >= len(shapes.P) {
				log.Fatalf("duplicated index in --drop=...%d...%d", x, x)
			}
			shapes.P = append(shapes.P[:x], shapes.P[x+1:]...)
		}
	}

	haveShapes := *before && shapes != nil && len(shapes.P) != 0
	haveCuts := cuts != nil && len(cuts.P) != 0
	haveUnion := *after && shapes != nil && len(shapes.P) != 0
	haveInverse := *inverse != 0 && shapes != nil && len(shapes.P) != 0

	var prefix []string
	if haveShapes {
		prefix = append(prefix, "'-' with lines title 'before'")
	}
	if haveCuts {
		prefix = append(prefix, "'-' with lines title 'cuts'")
	}
	if haveInverse {
		prefix = append(prefix, "'-' with lines title 'inverse'")
	} else if haveUnion {
		prefix = append(prefix, "'-' with lines title 'union'")
	}

	if len(prefix) == 0 {
		log.Fatal("nothing to display")
	}

	out := os.Stdout
	if *oPoly != "" {
		out, err = os.Create(*oPoly)
		if err != nil {
			log.Fatalf("Unable to generate polygon.Shapes output %q: %v", *oPoly, err)
		}
		defer out.Close()
	} else if *oSVG != "" {
		out, err = os.Create(*oSVG)
		if err != nil {
			log.Fatalf("Unable to generate SVG output %q: %v", *oSVG, err)
		}
		defer out.Close()
	} else if *dest != "" {
		out, err = os.Create(*dest)
		if err != nil {
			log.Fatalf("Unable to generate output %q: %v", *dest, err)
		}
		defer out.Close()
	}

	if *oSVG == "" && *oPoly == "" {
		fmt.Fprintf(out, "plot %s\n", strings.Join(prefix, ", \\\n     "))
		if haveShapes {
			plotData(out, shapes)
		}
		if haveCuts {
			plotData(out, cuts)
		}
	}

	if *inflate != 0 {
		for i := range shapes.P {
			if err := shapes.Inflate(i, *inflate); err != nil {
				log.Fatalf("Failed to inflate shape %d: %v", i, err)
			}
		}
	}
	if haveUnion {
		shapes.Union()
	}
	if haveInverse {
		shapes, err = shapes.Negative(*inverse)
		if err != nil {
			log.Fatalf("Failed to generate negative: %v", err)
		}
	}

	if *oPoly != "" {
		enc := json.NewEncoder(out)
		if err := enc.Encode(shapes); err != nil {
			log.Fatalf("failed to json encode %q: %v", *oPoly, err)
		}
		return
	}

	var lines []polygon.Line
	if *hatch != 0 {
		var holes []int
		for i, s := range shapes.P {
			if s.Hole {
				holes = append(holes, i)
			}
		}
		for i, s := range shapes.P {
			if s.Hole {
				continue
			}
			stripes, err := shapes.Hatch(i, *scribe, *hatch, *hatch/2, *hAngle/180*math.Pi, holes...)
			if err != nil {
				log.Fatalf("failed to hatch shape[%d] with these holes: %v", i, holes)
			}
			lines = append(lines, stripes...)
		}
	}

	if *oSVG != "" {
		if *flip {
			for i := range lines {
				lines[i].From.Y *= -1
				lines[i].To.Y *= -1
			}
			shapes = svgpoly.Flip(shapes)
		}
		if *outline != "" {
			svgpoly.OutlineColor = *outline
		}
		if *inline != "" {
			svgpoly.InlineColor = *inline
		}
		if *backing != "" {
			svgpoly.BackingColor = *backing
		}
		if *hatching != "" {
			svgpoly.HatchColor = *hatching
		}
		if *fill != "" {
			svgpoly.ShapeColor = *fill
		}
		if *hole != "" {
			svgpoly.HoleColor = *hole
		}
		if err := svgpoly.SVG(shapes, out, *scribe, lines); err != nil {
			log.Fatalf("Failed to render SVG output: %v", err)
		}
	} else if haveUnion {
		plotData(out, shapes, lines...)
	}
}
