// Program outline imports SVGs (primarily those generated by KiCad)
// and converts them into polygon.Shapes that outline the overlapping
// input data. It outputs in the form of a gnuplot inline script.
package main

import (
	"flag"
	"fmt"
	"io"
	"log"
	"math"
	"os"
	"strings"

	"zappem.net/pub/graphics/svger"
	"zappem.net/pub/graphics/svgpoly"
	"zappem.net/pub/math/polygon"
)

var (
	src     = flag.String("svg", "", "input SVG file")
	dest    = flag.String("dest", "", "output gnuplot script filename")
	oSVG    = flag.String("osvg", "", "output representation in SVG format")
	debug   = flag.Bool("debug", false, "enable more debugging output")
	before  = flag.Bool("before", false, "show polygons before creating union")
	after   = flag.Bool("after", true, "show polygons after creating union")
	scribe  = flag.Float64("scribe", 0.1, "pen scribing size (for rounding circles and --osvg)")
	inflate = flag.Float64("inflate", 0.0, "inflate outlines by this value")
	hatch   = flag.Float64("hatch", 0.0, "hatch the polygons with this spacing")
	hAngle  = flag.Float64("hatch-angle", 45.0, "hatch pattern is at this angle")
)

// plotData outputs the polygon data into a gnuplot format.
func plotData(out io.Writer, s *polygon.Shapes, lines ...polygon.Line) {
	if s == nil {
		log.Fatal("Unable to plot empty shapes")
	}
	fmt.Fprintln(out, "# X Y")
	for i, p := range s.P {
		for _, pt := range p.PS {
			fmt.Fprintf(out, "%g %g\n", pt.X, pt.Y)
		}
		fmt.Fprintf(out, "%g %g\n", p.PS[0].X, p.PS[0].Y)
		if i != len(s.P)-1 {
			fmt.Fprintln(out)
		}
	}
	for _, line := range lines {
		fmt.Fprintf(out, "\n%g %g\n%g %g\n", line.From.X, line.From.Y, line.To.X, line.To.Y)
	}
	fmt.Fprintln(out, "e")
}

func main() {
	log.Default().SetFlags(log.Lshortfile | log.Ldate | log.Lmicroseconds)
	flag.Parse()
	svger.Debug = *debug

	// shapes are closed (filled) polygons.
	// cuts are outlines with no substance.
	shapes, cuts, err := svgpoly.LoadSVG(*src, *scribe)
	if err != nil {
		log.Fatalf("Failed to load --svg=%q: %v", *src, err)
	}

	haveShapes := *before && shapes != nil && len(shapes.P) != 0
	haveCuts := cuts != nil && len(cuts.P) != 0
	haveUnion := *after && shapes != nil && len(shapes.P) != 0

	var prefix []string
	if haveShapes {
		prefix = append(prefix, "'-' with lines title 'before'")
	}
	if haveCuts {
		prefix = append(prefix, "'-' with lines title 'cuts'")
	}
	if haveUnion {
		prefix = append(prefix, "'-' with lines title 'union'")
	}

	if len(prefix) == 0 {
		log.Fatal("nothing to display")
	}

	out := os.Stdout
	if *dest != "" {
		out, err = os.Create(*dest)
		if err != nil {
			log.Fatalf("Unable to generate output %q: %v", *dest, err)
		}
		defer out.Close()
	} else if *oSVG != "" {
		out, err = os.Create(*oSVG)
		if err != nil {
			log.Fatalf("Unable to generate SVG output %q: %v", *oSVG, err)
		}
		defer out.Close()
	}

	if *oSVG == "" {
		fmt.Fprintf(out, "plot %s\n", strings.Join(prefix, ", \\\n     "))
		if haveShapes {
			plotData(out, shapes)
		}
		if haveCuts {
			plotData(out, cuts)
		}
	}

	if haveUnion {
		shapes.Union()
		if *inflate != 0 {
			for i := range shapes.P {
				if err := shapes.Inflate(i, *inflate); err != nil {
					log.Fatalf("Failed to inflate shape %d: %v", i, err)
				}
			}
		}
	}

	var lines []polygon.Line
	if *hatch != 0 {
		var holes []int
		for i, s := range shapes.P {
			if s.Hole {
				holes = append(holes, i)
			}
		}
		for i, s := range shapes.P {
			if s.Hole {
				continue
			}
			stripes, err := shapes.Hatch(i, *scribe, *hatch, *hatch/2, *hAngle/180*math.Pi, holes...)
			if err != nil {
				log.Fatalf("failed to hatch shape[%d] with these holes: %v", i, holes)
			}
			lines = append(lines, stripes...)
		}
	}

	if *oSVG != "" {
		if err := svgpoly.SVG(shapes, out, *scribe, lines); err != nil {
			log.Fatalf("Failed to render SVG output: %v", err)
		}
	} else {
		plotData(out, shapes, lines...)
	}
}
